Kinvey/swift-sdk

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/KinveyDateTransform.swift
- Kinvey/KinveyTests/DataTypeTestCase.swift
The ISO8601 Date Formatter in the ObjectMapper library is insufficient to handle all cases of Kinvey dates. This PR adds a formatter that supports the following formats - 
* yyyy-MM-dd'T'HH:mm:ss.SSS'Z' -> default date string written by this transform
* yyyy-MM-dd'T'HH:mm:ss.SSS+ZZZZ -> date with time offset (e.g. +0400, -0500)
* ISODate("yyyy-MM-dd'T'HH:mm:ss.SSSZ") -> backward compatible with Kinvey 1.x
> New date formatter for kinvey ISO dates

- Kinvey/Kinvey/User.swift
The iOS SDK has "resetPassword" in several flavors, which seems unnecessary. The class method that takes usernameOrEmail seems adequate. 
I've left the instance method as well, just because it provides a shorthand way to reset the current user's password. Other methods are now deprecated.
> Deprecation of extraneous "reset password" methods

- Kinvey/Kinvey/Cache.swift
- Kinvey/Kinvey/Operation.swift
- Kinvey/Kinvey/Persistable.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/StoreTestCase.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
This fixes the issue (MLIBZ-1590), of Realm being accessed from multiple threads. The root cause of the issue was the `detach` method in `RealmCache.swift`. When detaching objects, nested objects are not properly detached. As a result, any subsequent attempt to access the nested objects results in a crash.
Tests Performed:
I modified unit tests locally to test the fix. The proper test for this fix will look more like an integration test. I plan to push it out soon, but didn't want to hold up the review.
> When detaching objects from Realm, perform a deep copy

- Makefile
Modified the build script to add XCGLogger in the build output package.
> Add XCGLogger to the build package

- Kinvey/Kinvey/KinveyDateTransform.swift
Fixed Jira ticket MLIBZ-1591. 
`KinveyDateTranform`did not have a public initializer, resulting in a compilation error when used outside the `Kinvey` module.
> Added public initializer to KinveyDateTransform

- Kinvey/Kinvey/Error.swift
- Kinvey/KinveyTests/ErrorTestCase.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Better error messages for `Kinvey.Error` objects as described in the issue https://github.com/Kinvey/ios-library/issues/173
`Kinvey.Error` now conforms to `LocalizedError`
Unit Test changed accordingly
> MLIBZ-1394: Better error message

- Carthage/Checkouts/NSPredicate-MongoDB-Adaptor/MongoDBPredicateAdaptor.m
- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/Entity.swift
- Kinvey/Kinvey/Geolocation.swift
- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/Kinvey/Metadata.swift
- Kinvey/Kinvey/Persistable.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
- Kinvey/KinveyTests/Person.swift
- Kinvey/KinveyTests/QueryTest.swift
Solves the problem of perform geolocation queries in the backend and locally
- NSPredicate -> MongoDB adaptor
- Local cache
- Test geolocation queries with circles with a radio
- Test geolocation queries with polygons (which includes the use case of boxes / rectangles)
> MLIBZ-1167: Geolocation Queries

- Kinvey/Kinvey/Entity.swift
- Kinvey/Kinvey/Persistable.swift
- Kinvey/Kinvey/Query.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/Book.swift
- Kinvey/KinveyTests/CacheStoreTests.swift
- Kinvey/KinveyTests/QueryTest.swift
This is a solution to solve the limitation around mapping arrays in your entity class.
- Creating new types that are literal convertible like `String`, `Int`, `Float`, `Double` and `Bool`
- Adding new `Transform` types to convert between `List` and `Array` values
- Overloading the `<-` operator in order to use the `Transform` types above
- Tested converting queries when running against the local cache. Queries like:
`authorNames contains 'Victor'`
`subquery(authorNames, $authorNames, $authorNames like[c] 'Vic*').$count > 0`
> MLIBZ-1587: adding support for mapping array/list properties

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/Acl.swift
- Kinvey/Kinvey/File.swift
- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/KinveyTests/AclTestCase.swift
- Kinvey/KinveyTests/FileTestCase.swift
- Kinvey/KinveyTests/UserTests.swift
Fixes MLIBZ-1667 - the ACL properties set on a file object are not being POSTed to the backend.
* The `File` class now extends `Entity`. This allows us to define JSON mappings for it like other kinvey entities.
* All serialization and deserialization of `File` object is via JSON mapper.
* (Proposed) - since `Entity` maps `_id` already, is there any value to having a separate `fileId`? The proposal is to remove `fileId`, although that'll be a breaking change.
* (Proposed) - current file APIs pass the `File` object as a reference. In all of our other data APIs, we build new instances in response to `save` or `fetch` calls. Is there a reason to use `File` as references? The proposal is to treat `File` like any data object. The instance received in the completion block is a new object.
* …
> MLIBZ-1667: WIP fixed file json mapping

- Kinvey/Kinvey/Entity.swift
- Kinvey/Kinvey/ObjCRuntime.swift
- Kinvey/Kinvey/String.swift
- Kinvey/KinveyTests/Person.swift
Handling cases where protocols are @objc compatible
* Now our `Entity` base class ignore protocols that are @objc compatible
* Adding a `wear var delegate: Protocol?` to test if the unit tests will crash
> MLIBZ-1726: ignoring protocol properties

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/Error.swift
- Kinvey/Kinvey/HttpResponse.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/Kinvey/LocalResponse.swift
- Kinvey/Kinvey/Response.swift
- Kinvey/KinveyApp/AppDelegate.swift
- Kinvey/KinveyTests/PushTestCase.swift
Missing APNS push configuration in the console should return an error
* Building the right proper error
* Unit test mocking an error response from the backend
> MLIBZ-1713: throwing a proper error if the push configuration is missing in the backend

- Kinvey/Kinvey/Push.swift
Making sure the device is being deleted after unregister for push succeeds
* Deleting the device token from keychain
* No unit test since push does not work in the simulator
> MLIBZ-1757: deleting device token after unregister for push notifications

- Kinvey/Kinvey/Kinvey.h
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Local query should not crash if a field is not mapped in the entity class
* Make the local cache ignore `Invalid property name` errors
* Unit Test runs a local query with a non-mapped field
> MLIBZ-1660: Local query should not crash if field not found on entity

- Kinvey/Kinvey/DataStore.swift
- Kinvey/Kinvey/Endpoint.swift
- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/Kinvey/PendingOperation.swift
- Kinvey/Kinvey/PushOperation.swift
- Kinvey/Kinvey/Query.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/Kinvey/RealmSync.swift
- Kinvey/KinveyApp/AppDelegate.swift
- Kinvey/KinveyTests/PerformanceProductTestCase.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Making push operations able to run in parallel
Performance tests jump from around `30s` to `5s` to push 100 records
* Not making pending operations depending each other so they can run in parallel
* Unit Test to make sure that only one pending operation is stored by entity
> MLIBZ-1723: making push operations able to run in parallel

- Kinvey/Kinvey/JsonResponseParser.swift
- Kinvey/Kinvey/ResponseParser.swift
- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/UserTests.swift
Lookup Users are not returning the proper User type if a custom user type is being used.
* Make the user parse consider the custom user type set by the user
* Unit Test to cover the use case as described
> MLIBZ-1770: lookup custom user types

- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/UserTests.swift
Missing feature from v1 which allows an user instance to refresh data
* Added a new method in the `User` class
* Unit Test added with mocking response
> MLIBZ-1788: user refresh

- Kinvey/Kinvey/JsonResponseParser.swift
- Kinvey/Kinvey/Keychain.swift
- Kinvey/KinveyTests/UserTests.swift
After a relaunch the custom user type is not properly loaded
* Keychain was causing the problem
* Same unit tests, just added one more line to check if the keychain is returning the proper custom user type
> MLIBZ-1800: custom user downcasting

- Kinvey/Kinvey/Push.swift
- Kinvey/KinveyTests/PushTestCase.swift
Returning an error through completion handler instead of crash
* Push class in order to not crash
* Overload the unregister method to complain with the `Result<Success, Failure>` pattern
* Add a new unit test to cover the use case
> MLIBZ-1809: unregister push token crash

- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
- Kinvey/KinveyTests/QueryTest.swift
Encoding "+" inside URL queries
* Workaround since `URLQueryItem` does not encode "+" in URL queries
* Unit test that saves and then try to retrieve by query a string value that contains a plug sign, like "C++" for example
> MLIBZ-1927: query with plus sign

- Kinvey.podspec
Removing support for tvOS for now since seems to be a problem with PubNub + tvOS + CocoaPods
* Removing support for tvOS for now
* Tested manually
> MLIBZ-1936: removing support for tvOS for now

- Kinvey/Kinvey/Error.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/Kinvey/PushOperation.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Crash was happening when a DLC/BL is returning an empty body error
* Avoiding force unwrap optionals when building error objects
* No need for additional unit test
> MLIBZ-1951: crashing with empty body error

- Kinvey/Kinvey/DataStore.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
Queries must be translated if the property has an alias name
Bug detected during random look at the code
* Fix for count() method
* New unit test to cover the use case
> MLIBZ-1970: bug fix for count not translating queries

- Kinvey/Kinvey/ObjCRuntime.swift
- Kinvey/KinveyTests/KinveyTestCase.swift
- Kinvey/KinveyTests/QueryTest.swift
Make sure the query `Query(format: "obj._id == %@", 30)` is being converted to `query={"obj._id":30}` and not `query={"obj":{"_id":30}}`
* No real changes
* Adding more test scenarios for query equals operator
> MLIBZ-1979: unit test for query eq operator

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/Realtime.swift
- Kinvey/KinveyTests/RealtimeAclTestCase.swift
LiveStreamAcl default constructor was internal, but should be public
* Adding a explicit constructor for LiveStreamAcl
* Unit test added to check if the constructor with no parameters is available
> MLIBZ-2050: LiveStreamAcl default constructor must be available

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/File.swift
- Kinvey/KinveyTests/FileTestCase.swift
- Kinvey/KinveyTests/MyFile.swift
Subclassing File was not possible because mapping() must be open and not just public
* `File.mapping()` was not `open`
* `MyFile` used in tests is now in its own file so we don't import internal methods from the library causing the unit test to failure catching this bug
> MLIBZ-2040: Subclassing File

- Kinvey/Kinvey/ObjCRuntime.swift
- Kinvey/Kinvey/Persistable.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/CacheStoreTests.swift
- Kinvey/KinveyTests/DataTypeTestCase.swift
Implementing cascade delete since `find()` operations was ending up accumulating wasted objects in the database
* During `save()` the cache implementation now performs deletes on nested objects
* Making sure the nested objects are also being deleted
> MLIBZ-2046: cascade delete

- Kinvey/Kinvey/Entity.swift
- Kinvey/Kinvey/FindOperation.swift
- Kinvey/Kinvey/GetOperation.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/KinveyTests/DataTypeTestCase.swift
- Kinvey/KinveyTests/DeltaSetCacheTestCase.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
Make _id required, but not _kmd and _acl
* `Entity` now validates if `_id` is present
* Unit test to check if is ok if `_kmd` or `_acl` is missing
* Unit test to check if `_id` is missing in a `find(byId:)` throws an error
* Unit test to check if `_id` is missing in a `find()` returns an empty array
> MLIBZ-1549: _id required, but not _kmd and _acl

- Kinvey/Kinvey/Endpoint.swift
- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/Kinvey/RequestFactory.swift
- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/UserTests.swift
- Kinvey/SSOApp/SSOApp1Tests/SSOApp1Tests.swift
- Kinvey/SSOApp/SSOApp2Tests/SSOApp2Tests.swift
Make the `logout()` async which will end up invalidating the current auth token
* Adding optional parameters to the `logout()` method
* Unit testing mocking the response from the server
> MLIBZ-1502: logout async

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/Cache.swift
- Kinvey/Kinvey/CacheManager.swift
- Kinvey/Kinvey/Client.swift
- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/KinveyMacAppTests/MacOSOnlyTestCase.swift
- Kinvey/KinveyTests/CacheStoreTests.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Cache path on macOS was `~/Documents/<kid>`, but should be `~/Library/Application Support/<bundle id>/<kid>`
* `Kinvey.swift` now contains a `internal` `cacheBasePath` and the rest of the code should use it
* Unit test that check if the cache is being saved in the right path
> MLIBZ-2058: fixing the cache path when running on macOS

- Kinvey/Kinvey/Push.swift
Bug detected after Xcode 9 came out
* Making sure `UIApplication.shared.registerForRemoteNotifications()` is being called in the main thread
* Hard to have a unit test for since this is around push notifications
> MLIBZ-2088: bugfix register for push must be called in main thread

- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/Kinvey/MIC.swift
- Kinvey/Kinvey/RequestFactory.swift
- Kinvey/Kinvey/URLSessionTaskRequest.swift
Allow custom URLSessions for background calls for example
* Added a property called `urlSession` in the `Options` class
* Changed all places where a URLSession is used
* No need to add unit tests
> MLIBZ-2096: allow custom URLSessions

- Kinvey/BackgroundFetch/AppDelegate.swift
Bugfix for the infinite loop in case the user forgets to add the `dynamic` keyword in the property
* Fixing the `ObjCRuntime` class to not get stucked in a infinite loop in case the property does not have a `dynamic` keyword
* Since this is a infinite loop it's hard to find a way to write a unit test for it
> MLIBZ-2095: bugfix for the infinite loop if dynamic keyword is not used

- Kinvey/Kinvey/RealmSync.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Bugfix for sync since it was not filtering by collection
* Filtering pending operations by collection at `RealmSync`
* Checking if the `syncCount()` and the result of a `sync()` calls results in the expected number of entities being pushed
> MLIBZ-2102: bugfix for sync since it was not filtering by collection

- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/DataTypeTestCase.swift
- Makefile
- scripts/devcenter-release/main.swift
MLIBZ-2111: bugfix transforms were being ignored when saving object using dynamic Realm
* `RealmCache.save()` using dynamic Realm was not considering cases where a transform needs to be applied
* New unit test added to test a scenario where a Date, which requires some transformation to JSON, is being saved to Realm
> MLIBZ-2111: bugfix transforms were being ignored when saving object using dynamic Realm

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/AggregateOperation.swift
- Kinvey/Kinvey/CountOperation.swift
- Kinvey/Kinvey/DataStore.swift
- Kinvey/Kinvey/FindOperation.swift
- Kinvey/Kinvey/GetOperation.swift
- Kinvey/Kinvey/PullOperation.swift
- Kinvey/Kinvey/ReadOperation.swift
- Kinvey/Kinvey/ValidationStrategy.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
Allow data validation strategies upfront before return the lazy results
* Introduces an optional validation in the `FindOperation`
* Coming soon after we agree with the solution
> MLIBZ-2122: Allow data validation upfront

- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/Kinvey/Realtime.swift
- Kinvey/Kinvey/RequestFactory.swift
- Kinvey/KinveyTests/RealtimeTestCase.swift
Allow users to retrieve the acl for a live stream
* Add a new method call `streamAccess()`, following a similar name to grant access, which is `grantStreamAccess()`
* Add a check in a existing unit test
> MLIBZ-2087: allow users to retrieve the acl for a live stream

- Kinvey/Kinvey/Error.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/Kinvey/PushOperation.swift
- Kinvey/KinveyTests/AclTestCase.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
Find by `_id` must return `EntityNotFound` error
* Added one more case for the `Error` enum
* Unit test added to cover the situation when the entity was not found
> MLIBZ-2246: find by id must return entity not found error

- Kinvey/Kinvey/Persistable.swift
Bugfix for the memory leak issue by changing a few structs to become classes since the Swift runtime allocation implementation is causing memory leaks in some cases
Here some simular cases around the `swift_slowAlloc` issue
https://bugs.swift.org/browse/SR-4518?jql=status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20text%20~%20%22swift_slowAlloc%22
* `AnyTransform` and `PropertyMap` are no longer structs, they are now classes
* No way to cover memory leaks using unit tests at this point
> MLIBZ-2309: bugfix for the memory leak

- Kinvey/Kinvey/Entity.swift
- Kinvey/Kinvey/Persistable.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Bugfix removing the usage o `Thread.threadDictionary` to avoid memory leaks
- Object mapping runs in a `OperationQueue` and is not anymore storying the results into `Thread.threadDictionary` since memory leaks were happening because of the Swift bridge / runtime
- Few changes to the Travis CI script to be able to compile and run the unit tests
- Unit Test that measure the memory consumed in a long loop to make sure no memory is leaking
> MLIBZ-2309: bugfix removing the usage o Thread.threadDictionary to avoid memory leaks

- Kinvey/Kinvey/Client.swift
Adding Options for Client constructor
- Adding optional parameter in an existing constructor
- Simple addition, no need for unit test
> MLIBZ-2343: adding Options for Client

- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/FileTestCase.swift
FileStore proper result types for sync wait calls
- Setting the result for each request returned
- Made some additions to existing unit tests
> MLIBZ-2359: FileStore proper result types for sync wait calls

- Kinvey/Kinvey/Error.swift
- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/KinveyTests/KinveyTestCase.swift
- Kinvey/KinveyTests/MockKinveyBackend.swift
- Kinvey/KinveyTests/UserTests.swift
Handling a user lockdown case by automatically logout the user if a 401 response is returned from the server
- Checking if a 401 response is returned and then logout the user
- Unit test to mock the situation
> MLIBZ-2210: handling user lockdown

- Kinvey/Kinvey/Client.swift
- Kinvey/KinveyTests/ClientTestCase.swift
Changing the default MIC Version to v3
- The default value for `Client.micApiVersion` is now `.v3`
- We already have unit tests for that
> MLIBZ-2400: Changing the default MIC Version to v3

- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
Adding Swift version to User-Agent HTTP header
- Changing all HTTP requests to add the Swift version in the `User-Agent` header
- Unit test changed to check if the Swift version is present
> MLIBZ-1568: adding Swift version to User-Agent HTTP header

- Kinvey/Kinvey/Client.swift
- Kinvey/Kinvey/HttpRequest.swift
Removing compiler warning for `Client.timeout`
- `Client.timeout` is now a shortcut for `Client.options.timeout`
- Unit tests already cover the changes
> MLIBZ-2210: removing compiler warning for Client.timeout

- Kinvey/Kinvey/Client.swift
- Kinvey/Kinvey/DataStore.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
Removing Cache for DataStore instances, since there's no need for them and could cause trouble if you have multiple configurations for the same DataStore
- `Client` does not cache instances of DataStores anymore
- TBD
> MLIBZ-2408: Removing DataStore Cache instances

- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/Kinvey/Query.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
`removeAll()` must generate a request like `/appdata/kid/collection?query={}` instead of only `/appdata/kid/collection`
- Be able to force a `query` param when is needed
- Unit Test added to cover the use case
> MLIBZ-2409: removeAll() request

- Kinvey/Kinvey/Credential.swift
- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/KinveyTests/UserTests.swift
`authServiceID` using a BasicAuth credential for MIC calls
- For `/oauth/token` and refresh token calls we are now considering the `authServiceID` parameter
- New unit test based in an existing one
> MLIBZ-2402: authServiceID using a BasicAuth credential

- Kinvey/Kinvey/Entity.swift
- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/EntityTestCase.swift
- Kinvey/KinveyTests/UserTests.swift
`User` and `Entity` classes now conforms to Hashable and Equatable
- Adding methods for Hashable and Equatable in the `User` and `Entity` class
- Unit tests to double check Hashable and Equatable
> MLIBZ-2439: User and Entity classes now conforms to Hashable and Equatable

- Kinvey/Kinvey/Cache.swift
- Kinvey/Kinvey/DataStore.swift
- Kinvey/Kinvey/Entity.swift
- Kinvey/Kinvey/Persistable.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/MemoryCache.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Using the `ThreadSafeReference` from `Realm` to allow detached objects observe for changes
- Observe for changes in the local cache either by `query` or `object`
- Some wrappers added to allow future different implementations
- Unit tests to observe `objects` and `queries`
> MLIBZ-2099: thread safe reference observe

- Kinvey/Kinvey/Query.swift
- Kinvey/KinveyTests/QueryTest.swift
Bugfix for query translation for non-entity classes
- Query translations must include classes that implements `Mappable` but do not extends from `Entity`
- Unit test to cover a mixed query translation including an entity class and a non-entity class
> MLIBZ-2438: bugfix for query translation for non-entity classes

- Kinvey/Kinvey/Kinvey.swift
- Kinvey/KinveyTests/LogTestCase.swift
Default log level must be `.warning`
- `.warning` log level is set when the log is created
- Unit test changed to double check that
> MLIBZ-2475: default log level must be warning

- Kinvey/Kinvey/FindOperation.swift
- Kinvey/Kinvey/PullOperation.swift
- Kinvey/KinveyTests/DeltaSetCacheTestCase.swift
- Making sure to not save the query last sync date if skip and limit is being used
- `FindOperation` (which is also the base class for `PullOperation`) is now checking for `skip` and `limit` usage, but also considering other scenarios like `autoPagination` for example
- Unit test added to check the cache data
> MLIBZ-2485: skip and limit should not save the query last sync

- Kinvey/Kinvey/FindOperation.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
Bugfix for cancel find requests
- `FindOperation` uses `MultiRequest` for cases like `autoPagination` for example. We were not adding the child requests to the `multiRequest` instance in 2 situations, which was causing the bug. 
- Unit Test added. TDD approach.
> MLIBZ-2481: bugfix for cancel find requests

- Kinvey/Kinvey/PullOperation.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
When skip and limit is used we should not remove cached records
- `PullOperation` now checks if the `skip` and `limit` are `nil` to determine if local records should be deleted before save the records pulled from the server
- Unit Test added to reproduce the scenario described in the JIRA ticket
> MLIBZ-2490: pull with skip should not remove cached records

- Kinvey/Kinvey/FindOperation.swift
- Kinvey/KinveyTests/DeltaSetCacheTestCase.swift
Recovering when the delta set is not enabled in the backend
- Setting `FindOperation.deltaSet` to `false` if we detected the delta set feature is not enabled in the backend
- Unit Test
```
1. Enable auto-pagination and deltaset in a store and pull
2. Disable deltaset in the backend of an app and create 10 items in the collection
3. Pull with maxSizePerResultSet = 3
Expected result: Pull performs deltaset request that fails because the deltaset is not enabled in the backend and then a regular GET is made using auto-pagination and maxSizePerResultSet
```
> MLIBZ-2491: recovering correctly when the delta set is not available

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey.xcodeproj/xcshareddata/xcschemes/Kinvey-macOS.xcscheme
- Kinvey/Kinvey.xcodeproj/xcshareddata/xcschemes/Kinvey.xcscheme
- Kinvey/Kinvey/Geolocation.swift
- Kinvey/Kinvey/Persistable.swift
- Kinvey/KinveyApp/PerformanceTestData.swift
- Kinvey/KinveyApp/PerformanceTestMedData.swift
- Kinvey/KinveyTests/DataTypeTestCase.swift
- Kinvey/KinveyTests/EntityTestCase.swift
- Kinvey/SSOApp/SSOApp1/AppDelegate.swift
Removing compiler warnings and ignoring deprecation warnings for unit tests
- After Swift 4.1 changes the compiler was throwing some warnings
- Mainly `Persistable.swift` and Unit Tests
- No need for additional unit tests
> MLIBZ-2510: removing compiler warnings

- Kinvey/Kinvey/Cache.swift
- Kinvey/Kinvey/FindOperation.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/DeltaSetCacheTestCase.swift
- Kinvey/KinveyTests/MemoryCache.swift
When a 2nd or following requests fails in a auto pagination request, the last sync date should not be saved
- `FindOperation` should start a transaction before start performing the auto pagination requests
- Unit tests added (TDD)
> MLIBZ-2511: writing auto pagination requests inside a transaction

- Kinvey/Kinvey/Error.swift
- Kinvey/Kinvey/MIC.swift
- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/UserTests.swift
MIC v3 and above can now return `error` and `error_description` in the redirect uri
- `MIC.parseCode` now can handle when errors are returned
- Unit tests to cover this case (TDD)
> MLIBZ-2527: handling OAuth MIC errors in redirect uri

- Kinvey/Kinvey/Query.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/DeltaSetCacheTestCase.swift
Handling the situation when different fields are used between requests
- `RealmCache` and `_QueryCache` have one more property: `fields` which is a Array of Strings stored as a String separated by `,`
- Unit tests to cover different usages of fields
> MLIBZ-2428: enabling deltaset and fields operator in the query

- Kinvey/Kinvey/Error.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
Adding an specific error type for BL runtime errors
- New `Error` case
- Unit test that mocks a BL runtime error
> MLIBZ-723: BL runtime error stack trace

- Kinvey/Kinvey/Client.swift
- Kinvey/Kinvey/Push.swift
Deprecating methods that should be already deprecated a long time ago
- `Client` and `Push`
- No need
> MLIBZ-2557: adding missing methods to be deprecated

- Kinvey.podspec
Testing this again I actually figured the problem is actually a bug in CocoaPods that is solved after clear the CocoaPods cache folder like described here:
https://github.com/realm/realm-cocoa/issues/4758
- `Kinvey.podspec` file to support tvOS again for CocoaPods
- No need
> MLIBZ-1937: returning support for tvOS for CocoaPods

- .travis.yml
- Kinvey/Kinvey/Executor.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/Kinvey/RemoveOperation.swift
- Kinvey/KinveyTests/KinveyTestCase.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
- Makefile
Memory leak detected inside `DataStore.removeAll()`
- Making sure `for` loops are using `autoreleasepool` specially when many items are changed in the cache store
- Unit test that estimate a memory consumption
> MLIBZ-2582: fix for DataStore.removeAll() memory leak

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/CustomEndpoint.swift
- Kinvey/Kinvey/FindOperation.swift
- Kinvey/Kinvey/RealmSupport.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Bugfix to persist Swift.Codable in cache
- `Codable` entities cannot be persisted using the dynamic cache
- Added a unit test to test `pull()` a `find()` using a Sync DataStore
> MLIBZ-2620: bugfix to persist Swift.Codable in cache

- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/KinveyTestCase.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Better support for cascade deletes. In some cases the cascade delete `Acl` and `Metadata` were not working.
- `RealmCache` now covering updates.
- Small additions to existing unit test
> MLIBZ-2583: better support for cascade deletes

- Kinvey/Kinvey/Client.swift
- Kinvey/Kinvey/DataStore.swift
- Kinvey/Kinvey/Entity.swift
- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/FindOperation.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/Kinvey/Operation.swift
- Kinvey/Kinvey/Options.swift
- Kinvey/Kinvey/Persistable.swift
- Kinvey/Kinvey/PullOperation.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/Kinvey/RealmSync.swift
- Kinvey/Kinvey/Request.swift
- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Replacing Realm `ThreadSafeReference` usage since it can't be used inside a transaction
- Using the `primaryKey` as a reference instead of a `ThreadSafeReference` instance
- Unit test added to cover the use case
> MLIBZ-2636: replacing Realm ThreadSafeReference usage

- Kinvey/Kinvey/Entity.swift
- Kinvey/KinveyTests/Person.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Support for `List<T>` of primitive values like `List<StringValue>`, `List<IntValue>`, `List<FloatValue>`, `List<DoubleValue>` and `List<BoolValue>`
- Adding implementation for `Hashable`, `Equatable` and `Codable` for all primitive values
- New unit tests added
> MLIBZ-2646: support for list of primitive values for Codable

- Kinvey/Kinvey/User.swift
Current access on `User.encode` method is `public` which prevents overriding the method and in turn implementing a custom User class that conforms to the `Codable` protocol.
As Kinvey.Entity already has this method and it is `open` this change makes sense.
Related to comment in #311.
> Access on User.encode changed to open

- Kinvey/Kinvey/Cache.swift
- Kinvey/Kinvey/CountOperation.swift
- Kinvey/Kinvey/Entity.swift
- Kinvey/Kinvey/Error.swift
- Kinvey/Kinvey/FindOperation.swift
- Kinvey/Kinvey/Persistable.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyAppUITests/KinveyAppUITests.swift
- Kinvey/KinveyTests/DeltaSetCacheTestCase.swift
- Kinvey/KinveyTests/ForgotToCallSuper.swift
- Kinvey/KinveyTests/MemoryCache.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
- Kinvey/KinveyTests/Person.swift
- Kinvey/KinveyTests/RemoveAllMemoryLeakTests.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Realm have a limitation of keeping all objects in memory during a single large transaction. To avoid this situation we did a few changes around the cache layer.
- Request Start persisted is now from the `count()` 
- A few unit tests to ensure the cache data still consistent
> MLIBZ-2661: bugfix for large pull memory consumption

- Kinvey/Kinvey/Client.swift
- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/UserTests.swift
- Refresh User's method now checks if an existing `refresh_token` already exists and keep it as is
- `User.refresh()`
- Unit tests added to reproduce the issue
> MLIBZ-2637: refresh user should not update the refresh token

- Kinvey/Kinvey/Metadata.swift
- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/KinveyTestCase.swift
- Kinvey/KinveyTests/UserTests.swift
`EmailVerification` and `PasswordReset` metadata objects which are a part of `UserMetadata` do not have the `Codable` protocol implemented. This caused the `User` object to fail to initialize using `init(from:)` with the following error:
Implemented `Codable` for both `EmailVerification` and `PasswordReset` objects. Also updated the `mapping(map:)` method of `Metadata` as it seems it wasn't passing the correct keys to `map`.
Tested in an app making use of Kinvey user accounts, the above mentioned error is gone, checked that all of the data was correctly parsed and available inside the `User` instance.
> Codable for EmailVerification and PasswordReset metadata objects

- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
- Kinvey/KinveyTests/UserTests.swift
Storing the refresh token obtained by the `/oauth/token` endpoint
- `User` now have a `refreshToken` property 
- Same unit tests but making sure the refresh token value stored is the right value
> MLIBZ-2670: storing the correct refresh token

- Kinvey/Kinvey/Kinvey.swift
Adding basic support for command line apps
- CLI apps does not have a bundle, so because of that the `ProcessInfo.processName` should be used
- Same tests
> MLIBZ-2686: Adding basic support for command line apps

- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/UserTests.swift
Bugfix for crash when a non-objc property is set during refresh()
- `User` now overrides `setValue(_:forUndefinedKey:)` to avoid crashes
- A few changes in the custom user refresh unit test
> MLIBZ-2688: bugfix for crash when a non-objc property is set

- Kinvey/Kinvey/Client.swift
- Kinvey/KinveyTests/CacheMigrationTestCaseStep2.swift
- Kinvey/KinveyTests/ClientTestCase.swift
Multiple calls to initialize could cause unpredicted behaviours
- `Client.initialize()` now ensures is being called in the main thread and only once
- Unit tests added to cover the changes
> MLIBZ-1489: Prevent multiple calls to initialize client

- Kinvey/Kinvey/Date.swift
- Kinvey/Kinvey/Endpoint.swift
- Kinvey/Kinvey/Metadata.swift
- Kinvey/KinveyTests/AclTestCase.swift
- Kinvey/KinveyTests/CacheStoreTests.swift
- Kinvey/KinveyTests/DataTypeTestCase.swift
- Kinvey/KinveyTests/DateTestCase.swift
- Kinvey/KinveyTests/DeltaSetCacheTestCase.swift
- Kinvey/KinveyTests/FileTestCase.swift
- Kinvey/KinveyTests/KinveyTestCase.swift
- Kinvey/KinveyTests/MetadataTestCase.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
- Kinvey/KinveyTests/NoCacheTestCase.swift
- Kinvey/KinveyTests/StoreTestCase.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
- Kinvey/KinveyTests/UserTests.swift
Be able to store dates as ISO 8601 strings
- Users using `Codable` don't have an easy way to store dates as before
- No need for new unit tests
> MLIBZ-2725: Be able to store dates as ISO 8601 strings

- Kinvey/Kinvey/Query.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/DeltaSetCacheTestCase.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
- Kinvey/KinveyTests/QueryTest.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Allowing perform queries using KeyPath syntax
- Mainly the `Query` class and a few overload operators
- Same unit tests but now also checking the KeyPath syntax produce the same results
> MLIBZ-2777: Allowing perform queries using KeyPath syntax

- Kinvey/Kinvey/RealmCache.swift
- Kinvey/Kinvey/RealmSync.swift
Adding {public} to the signpost calls when handled strings
- Signpost calls now uses `%@` instead of `%s` for string formatting
> MLIBZ-2838: Bugfix crash on signpost calls

- Kinvey/Kinvey/DataStore.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
New version of SwiftLint detected a new warning
- Minor change how the `hashValue` is calculated. `hashValue` is deprecated and the new `Hasher` should be used instead
> SwiftLint warning fix

- Kinvey/Kinvey/Cache.swift
- Kinvey/Kinvey/DataStore.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/MemoryCache.swift
- Kinvey/KinveyTests/Person.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Allow `DataStore.clearCache()` to delete nested objects
- `DataStore.clearCache()` now have an optional parameter called `cascadeDelete` with the default value `false`
- Unit tests now tests `clearCache()` with and without cascade delete
> MLIBZ-2864: Allow clearCache() to delete nested objects

- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/CacheStoreTests.swift
- Kinvey/KinveyTests/Person.swift
Objects that contains `List` as nested objects were crashing during save calls
- List needs to be detached from Realm
- Unit test added to cover the scenario reported by the support ticket
> MLIBZ-2855: Realm Crash when saving objects inside a List

- Kinvey/Kinvey/CustomEndpoint.swift
- Kinvey/Kinvey/Date.swift
- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/Kinvey/JSONParser.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/Kinvey/Query.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/CacheStoreTests.swift
- Kinvey/KinveyTests/Person.swift
- Kinvey/KinveyTests/QueryTest.swift
Converting dates in queries to ISO 8601 so queries will return the expected values in both local and network calls
- JSON Decoder and Encoder now converts ISO 8601 by default
- Allow users to set custom JSON Decoder and Encoder
- Dates on queries converts into ISO 8601 but only for network calls
- Tests for query local and network calls
> MLIBZ-2870: Converting dates in queries to ISO 8601

- Kinvey/Kinvey/Executor.swift
- Kinvey/Kinvey/FindOperation.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/CacheStoreTests.swift
- Kinvey/KinveyTests/DeltaSetCacheTestCase.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
`Executor` was blocking the UI for long periods of time
- `RealmCache` does not uses `Executor` anymore, but because we lazy load Realm objects and those objects are locked to a thread we still need to use `Executor` in some spots
> MLIBZ-2873: blocking UI thread

- Kinvey/Kinvey/Client.swift
Making `Client.userChangedListener` public allows perform actions when the user is not present anymore, like in situations where the token expired for example
- `Client.userChangedListener` is now public
> MLIBZ-2888: Make Client.userChangedListener public

- Kinvey/Kinvey/DataStore.swift
Using the correct custom `Client` instance
- Minor fixes in the `DataStore` to allow use custom `Client` instances
- Same Unit Tests
> Using custom Client instance

- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/Kinvey/HttpResponse.swift
- Kinvey/Kinvey/RealmSync.swift
- Kinvey/KinveyTests/KinveyURLProtocol.swift
Bugfix: Missing JSON `Content-Type` HTTP Header
- Push multiple items requests were missing the `Content-Type` HTTP Header
- Adding a check (to existing tests) if the request is sent with the right HTTP `Content-Type` header
> MLIBZ-3133: Missing JSON Content-Type HTTP Header

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/KinveyTests/Book.swift
- Kinvey/KinveyTests/MultiInsertSpec.swift
Steps to reproduce:
1. Create a few items with sync store2. Push them - the request looks like that:
```
POST https://baas.kinvey.com/appdata/kid_SkpK--qCb/Book
X-Kinvey-API-Version: 5
X-Kinvey-Device-Info: {"sdk":"iOS","pv":"Simulator Platform Version Unknown (x86_64)","os":"iOS","md":"iPhone","hv":1,"ov":"12.4"}
User-Agent: Kinvey SDK 3.26.0 (Swift 5.0)
Authorization: Kinvey *************************
X-Kinvey-Request-Id: 82A51DC3-BB97-4203-AF08-D1B40C690C61
[{"authors":[],"title":"This 1 book"},{"authors":[],"title":"This 2 book"}]
```
Expected result: the items are saved as they are in the backend and the sync queue is clearedActual results only one items is saved and some properties are omitted. The response to the above looks like:
```
201 created
Location: …
```
> MLIBZ-3134: checking if all properties are sent correctly

- Kinvey/Kinvey/FileCache.swift
- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/RealmFileCache.swift
Allowing query into file metadata
- `FileStore`, `FileType` and `RealmFileCache`
- TBD
> MLIBZ-3188: Allowing query into file metadata

- Kinvey/Kinvey/HttpRequestFactory.swift
Multi-Client support was crashing because some network constructors were ignoring the options struct
- Loading client instance if present inside of an `Options` struct
- TBD
> fix: MLIBZ-3194, fixing multi-client support

- .travis.yml
- Kinvey/Kinvey/File.swift
- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/Kinvey/Keychain.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/KinveyTests/CacheMigrationTestCaseStep2.swift
- Kinvey/KinveyTests/FileTestCase.swift
- Kinvey/KinveyTests/MyFile.swift
- Makefile
Fixes issue [Custom properties of class inherited from `File` and adopting `Codable` protocol are not sent to the backend](https://kinvey.atlassian.net/projects/MLIBZ/issues/MLIBZ-3195)
Steps to reproduce:
1. Create a subclass of Kinvey `File`
2. Add some custom property
3. Implement `Codable` protocol adoption
4. Try to upload a file using this custom class
**Actual Result**:
Method `encode(to encoder: Encoder)` is not called. Any custom properties from the class are not sent to Kinvey.
**Expected Result**:
Custom properties are sent to Kinvey along with default `File` class properties.
* Make `File` conform to `JSONCodable` protocol
* Add implementations for `encode(to)` and `init(from)`
* Copy `EntityCodingKeys` values to `FileCodingKeys`
because `Codable` implementation methods must …
> fix: MLIBZ-3195, Codable support for File

- .travis.yml
- Kinvey/Kinvey/DataStore.swift
- Kinvey/Kinvey/Result.swift
- Makefile
Before this fix building all the platforms with `make build` failed because of the missing platforms in the PubNub downloaded binary.
* Add command-line options to Carthage build:
* `--cache-builds` greatly improves build times, especially when
diagnosing issues with any of the dependencies. Issue a warning to
clean the workspace if producing a release build.
* `--no-use-binaries` builds every dependency from source instead of
downloading it from the GitHub release. This ensures
correct binaries because it's possible that some of the
downloaded ones do not contain all platforms that we support
(e.g. PubNub v4.13.1 is missing tvOS and watchOS)
* Fix tuple warnings
> fix:  Carthage build uses cache and no binaries

- Kinvey/Kinvey.xcodeproj/xcshareddata/xcschemes/Kinvey-macOS.xcscheme
- Kinvey/Kinvey.xcodeproj/xcshareddata/xcschemes/Kinvey.xcscheme
- Kinvey/Kinvey/Error.swift
- Kinvey/Kinvey/PushOperation.swift
- Kinvey/Kinvey/SaveMultiOperation.swift
- Kinvey/KinveyTests/KinveyTestCase.swift
- Kinvey/KinveyTests/MultiInsertSpec.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
* Consistent `MultiSaveError` behavior
* Rename `message` to `error` to match the property
name in the SDKs for other languages
* `localizedDescription` returns `description` as it was with v4
of the API
* Implement all methods from the `LocalizedError` protocol
with `localizedDescription`
* Reenable parallel execution and `SyncStoreTestApi4` test class in 
`Kinvey` and `Kinvey-macOS` schemes. These were disabled in an effort 
to fix  sporadical failures which later turned out to be caused by missing 
`realm.refresh` calls.
* Double check evaluation handler in `wait(toBeTrue:)`
It is possible for the condition to not be evaluated even once if
all async actions have been completed prior to entering
`CFRunLoopRunInMode`. This fixes sporadic failures of some of the tests
on Travis CI
refs: …
> fix: Consistent MultiSaveError behavior

- .gitignore
- .travis.yml
- Kinvey/Kinvey/RealmSync.swift
- Kinvey/Kinvey/SaveMultiOperation.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
When the number of entities in a `save()` or `push()` request exceeds the max allowed in the request (100 entities), the entities should be broken down into multiple sets of the max amount allowed, and multiple multi-insert requests should be sent out. `push()` however didn't follow this logic.
refs https://kinvey.atlassian.net/browse/KDEV-1151
* Split into multiple `pendingOperations` when items to
sync are more than `maxSizePerRequest` (100)
* Remove `;` which are reported as linter warnings
* Add `.swiftpm` to `.gitignore`
* Test with the sample provided in the Jira item
* Add a test case for push with a number of items which is
1,1 times greater than the limit
> KDEV-1151: Respect maximum items per request limit on push

- .github/workflows/ci.yml
- Kinvey.podspec
- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/Info.plist
- Package.swift
Additional Changes:
* Fix Package.swift for SPM was not targeting minimum iOS 12
* Update CI workflow Xcode version to 13.2.1 for all tests
> release: v6.0.0
