- Kinvey/Kinvey/Entity.swift
- Kinvey/Kinvey/KinveyDateTransform.swift
- Kinvey/Kinvey/Metadata.swift
- Kinvey/Kinvey/Persistable.swift
- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/DataTypeTestCase.swift
- Kinvey/KinveyTests/KinveyTestCase.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
- Kinvey/KinveyTests/UserTests.swift
Added User metadata. The User class can now represent all the metadata fields in the backend.
> MLIBZ-1467: user metadata

- Kinvey/KinveyTests/CustomEndpointTests.swift
- Kinvey/KinveyTests/KinveyTestCase.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
- Kinvey/KinveyTests/UserTests.swift
Helper method for unit tests that need to expect a certain amount of time for something to be true
Rewrite the `waitValueForObject` to accept any type and not just `NSObject`s
Tests already exists, I just had to refactor them
> Helper method for unit tests

- Kinvey/KinveyTests/UserTests.swift
Unit test to test if the refresh token trigger enters in a infinite loop
No changes in the code itself since the unit test proved the infinite loop is not happening
* Test if the refresh token trigger enters in a infinite loop
> MLIBZ-1673: unit test to test if the refresh token trigger enters in a infinite loop

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/Operation.swift
- Kinvey/Kinvey/URLSessionTaskRequest.swift
Error message during the unit tests: `PromiseKit: Pending Promise deallocated! This is usually a bug`
* Change the internals to use Promises for Files 
* No additional tests needed
> MLIBZ-1548: pending promise deallocated bugfix

- Kinvey/Kinvey/File.swift
- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/KinveyTests/FileTestCase.swift
Fix if the fileId was set but the uploadURL still
* `uploadURL` needs to be fetched when is not present
* Unit test added, but not using mock responses
> MLIBZ-1718: fix if the fileId was set but the uploadURL still unknown

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey.xcodeproj/xcshareddata/xcbaselines/57A27C8A1C178F18000DF951.xcbaseline/32D957A1-12C4-4B8D-BA8E-AACD880BAB72.plist
- Kinvey/Kinvey.xcodeproj/xcshareddata/xcbaselines/57A27C8A1C178F18000DF951.xcbaseline/Info.plist
- Kinvey/Kinvey.xcodeproj/xcshareddata/xcschemes/Kinvey.xcscheme
- Kinvey/Kinvey/Cache.swift
- Kinvey/Kinvey/DataStore.swift
- Kinvey/Kinvey/Endpoint.swift
- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/Persistable.swift
- Kinvey/Kinvey/Query.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/PerformanceProductTestCase.swift
- Kinvey/KinveyTests/PushTestCase.swift
- Kinvey/KinveyTests/QueryTest.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Testing a pre-defined set of data to test performance fetching data
* Minor changes in the code to improve performance
* Unit tests to be able to collect performance numbers
> MLIBZ-1700: performance tests and minor improvements

- Kinvey/Kinvey/Entity.swift
- Kinvey/Kinvey/Persistable.swift
- Kinvey/KinveyTests/Book.swift
Convenient overload for <- operator to handle List<T> types
* Overload the <- operator to handle list of mappable objects
Current unit tests should also cover that
> MLIBZ-1521: default transform for arrays

- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/TaskProgressRequest.swift
- Kinvey/KinveyTests/FileTestCase.swift
Upload from input stream done properly
* Change the way we were uploading data if the data source was an input stream
* Unit Test to upload from an input stream
> MLIBZ-1725: upload from input stream

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/Client.swift
- Kinvey/Kinvey/Endpoint.swift
- Kinvey/Kinvey/Error.swift
- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/Kinvey/RequestFactory.swift
- Kinvey/KinveyTests/ClientTestCase.swift
Adding missing ping call that we used to have in v1 of the library
* `ping()` method added to `Client`
* Unit Test to test successful and failure cases
> MLIBZ-1735: ping call

- Cartfile.resolved
- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/AggregateOperation.swift
- Kinvey/Kinvey/Cache.swift
- Kinvey/Kinvey/CacheManager.swift
- Kinvey/Kinvey/CountOperation.swift
- Kinvey/Kinvey/DataStore.swift
- Kinvey/Kinvey/Endpoint.swift
- Kinvey/Kinvey/FindOperation.swift
- Kinvey/Kinvey/GetOperation.swift
- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/Kinvey/MemoryCache.swift
- Kinvey/Kinvey/Operation.swift
- Kinvey/Kinvey/PullOperation.swift
- Kinvey/Kinvey/PurgeOperation.swift
- Kinvey/Kinvey/PushOperation.swift
- Kinvey/Kinvey/ReadOperation.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/Kinvey/RemoveByIdOperation.swift
- Kinvey/Kinvey/RemoveByQueryOperation.swift
- Kinvey/Kinvey/RemoveOperation.swift
- Kinvey/Kinvey/RequestFactory.swift
- Kinvey/Kinvey/SaveOperation.swift
- Kinvey/Kinvey/SyncOperation.swift
- Kinvey/Kinvey/WriteOperation.swift
- Kinvey/KinveyTests/DeltaSetCacheTestCase.swift
- Kinvey/KinveyTests/KinveyTestCase.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Be able to run grouping and aggregation functions in the backend
* Added new methods to the `DataStore` class with some overloads to facilitate the usage of common functions like `count`, `sum`, `min`, `max` and `average`.
* Unit tests added to cover each aggregation method
> MLIBZ-1311: Grouping / aggregation functions

- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/UserTests.swift
Minor fix after merged
* Storing the new data in cache
* Unit Tests modified to check if the new data was persisted
> MLIBZ-1788: user refresh

- Kinvey/Kinvey/Client.swift
- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/Kinvey/Keychain.swift
- Kinvey/Kinvey/User.swift
Make the `_socialIdentity` property available
* Turn the `socialIdentity` public and the sub-properties like `facebook`, `twitter`, `googlePlus`, `linkedIn` and `kinvey`
* Same tests, nothing changed in terms of tests
> MLIBZ-1781: social identity

- Kinvey/Kinvey/CacheManager.swift
- Kinvey/Kinvey/FileCache.swift
- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/RealmFileCache.swift
- Kinvey/KinveyTests/FileTestCase.swift
Allow users to extend from `File` and create their own properties for files.
* Changes on `FileCache`, `RealmFileCache`, `CacheStore` and `CacheManager`
* Minor changes in the unit tests for Files to cover the use case
> MLIBZ-1796: custom file type

- Kinvey/Kinvey/Client.swift
- Kinvey/Kinvey/Endpoint.swift
- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/Kinvey/Keychain.swift
- Kinvey/Kinvey/MIC.swift
- Kinvey/Kinvey/RequestFactory.swift
- Kinvey/Kinvey/String.swift
- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/UserTests.swift
- Kinvey/SSOApp/SSOApp1/AppDelegate.swift
- Kinvey/SSOApp/SSOApp1Tests/SSOApp1Tests.swift
- Kinvey/SSOApp/SSOApp2/AppDelegate.swift
- Kinvey/SSOApp/Sources/ViewController.swift
Client ID added to loginWithMic call
* Optional parameter on every MIC call to specify the client id
* No additional unit tests
> MLIBZ-1833: client ID to loginWithMic call

- Kinvey/Kinvey/DataStore.swift
- Kinvey/Kinvey/FindOperation.swift
- Kinvey/Kinvey/PullOperation.swift
Provide a way to retrieve the count / results when delta set is being used
* Added a callback to return only the results obtained if delta set is enabled
* No need for additional unit test
> MLIBZ-1731: delta set count and completion handler

- Kinvey/Kinvey/Acl.swift
- Kinvey/Kinvey/AggregateOperation.swift
- Kinvey/Kinvey/Client.swift
- Kinvey/Kinvey/CustomEndpoint.swift
- Kinvey/Kinvey/DataStore.swift
- Kinvey/Kinvey/Entity.swift
- Kinvey/Kinvey/File.swift
- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/Geolocation.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/Kinvey/KinveyDateTransform.swift
- Kinvey/Kinvey/MIC.swift
- Kinvey/Kinvey/Metadata.swift
- Kinvey/Kinvey/Persistable.swift
- Kinvey/Kinvey/Realtime.swift
- Kinvey/Kinvey/Result.swift
- Kinvey/Kinvey/String.swift
- Kinvey/Kinvey/User.swift
Increase documentation coverage
* Adding basic documentation around the code base
* No changes in the code itself, so no need for additional unit tests
> MLIBZ-1933: Increase documentation coverage

- Makefile
- scripts/github-release/main.swift
Allowing a single action release
* Swift script to manage Github releases and improvements in the `Makefile`
* Not applicable
> MLIBZ-1665: script release to allow a single action release

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/KinveyTests/NoCacheTestCase.swift
Making sure that we don't create any cache files if there's no need
* No need to change any part of the code
* Improve the test to make sure no file is created
> MLIBZ-1747: making sure that we don't create any cache files if there's no need

- Kinvey/KinveyTests/FileTestCase.swift
No real change, just adding more unit tests to make sure we are handling non 2xx responses
* Only unit tests
* Unit tests for download and upload with status code not being 2xx
> MLIBZ-2005: unit tests for download and upload errors

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey.xcodeproj/xcshareddata/xcschemes/Kinvey-macOS.xcscheme
- Kinvey/Kinvey.xcodeproj/xcshareddata/xcschemes/Kinvey.xcscheme
- Kinvey/Kinvey/FindOperation.swift
- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/Kinvey/JsonResponseParser.swift
- Kinvey/Kinvey/Query.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyMacAppTests/PerformanceTest.swift
Log time elapsed for performance measure
* Add log statements in a few key methods
* No need
> MLIBZ-1974: log time elapsed in a few key methods

- .codebeatignore
- Kinvey/Kinvey/CustomEndpoint.swift
- Kinvey/Kinvey/DataStore.swift
- Kinvey/Kinvey/Endpoint.swift
- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/Kinvey/Realtime.swift
- Kinvey/Kinvey/User.swift
Improving codebeat score
* Changes are based in the Codebeat report
* No changes needed
> MLIBZ-1934: improving codebeat score

- Kinvey/Kinvey/ObjCRuntime.swift
- Kinvey/Kinvey/Persistable.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/DataTypeTestCase.swift
Property Mapping missing properties when you have a List<T>
* `<-` operator was forgetting to register the property names and transformers
* Unit tests to check if all properties are mapped properly
> MLIBZ-2042: Property Mapping missing properties when you have a List<T>

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/Error.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/Kinvey/MIC.swift
- Kinvey/Kinvey/PushOperation.swift
- Kinvey/KinveyMacAppTests/RealtimeMacAppTests.swift
- Kinvey/KinveyTests/AclTestCase.swift
- Kinvey/KinveyTests/ErrorTestCase.swift
- Kinvey/KinveyTests/RealtimeTestCase.swift
LiveService ACL unit tests were missing
* `debug` added to `Error.unauthorized`
* New unit tests added to test ACL for publishers and subscribers
> MLIBZ-2051: LiveService ACL unit tests

- Kinvey/Kinvey/FileStore.swift
Bug fix for resumable uploads
* Create new methods call `create()` to allow create the bucket and keep the `fileId` and `_uploadURL` so we can resume the upload
* In case of `308` responses but there's no `Range` header it means the bucket still empty, so just send the file from the beginning
* No need for additional tests
> MLIBZ-519: bug fix for resumable uploads

- Kinvey/Kinvey/MIC.swift
- Kinvey/Kinvey/User.swift
- Kinvey/KinveyApp/Base.lproj/Main.storyboard
- Kinvey/KinveyApp/MICLoginViewController.swift
- Kinvey/KinveyTests/UserTests.swift
Support for SFAuthenticationSession (new iOS 11 feature)
* Adding new case for `MICUserInterface` called `safariAuthenticationSession`
* Added option to the test app
> MLIBZ-2106: Support for SFAuthenticationSession (new iOS 11 feature)

- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/UserTests.swift
Social Identity was not being persisted
* Social Identity struct mapping was wrong
* Adding assertions on an existing unit test
> MLIBZ-2169: fix to persist socialIdentity

- Carthage/Checkouts/NSPredicate-MongoDB-Adaptor/MongoDBPredicateAdaptor.swift
- Kinvey/Kinvey/Client.swift
- Kinvey/Kinvey/DataStore.swift
- Kinvey/Kinvey/Entity.swift
- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/Kinvey/ObjCRuntime.swift
- Kinvey/Kinvey/String.swift
- Kinvey/Kinvey/User.swift
Removing warnings after we upgrade to Swift 4
* Removing compiler warnings
* No changes needed
> removing warnings for Swift 4 and above

- .travis.yml
- Kinvey/Kinvey/Persistable.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/Book.swift
- Kinvey/KinveyTests/DataTypeTestCase.swift
- Kinvey/KinveyTests/FileTestCase.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
- Makefile
Bugfix for property mapping in nested objects
* `RealmCache` now considers nested objects for property mapping and not only nested arrays using `List<>`
* Unit test added to reproduce the use case
> MLIBZ-2306: bugfix for property mapping in nested objects

- .codeclimate.yml
- Kinvey/Kinvey/Client.swift
- Kinvey/Kinvey/Migration.swift
- Kinvey/KinveyTests/ClientTestCase.swift
- Kinvey/KinveyTests/UserTests.swift
Adding instanceID implementation
- Overloading `Client` constructor and `initialize()` method
- Unit test to check if the URLs were changed
> MLIBZ-2337: adding instanceID implementation

- Kinvey/Kinvey/Endpoint.swift
Send `scope` param to all MIC versions
- Removing the `if` statement and send to all versions
- TBD
> MLIBZ-2411: send scope param to all mic versions

- Kinvey/Kinvey/DataStore.swift
- Kinvey/KinveyTests/RealtimeTestCase.swift
Live Service messages not coming when strict permissions are used
- When strict permissions are used, the channel name includes the `userId`
- `DataStore.subscribe` now also listen for messages with strict permissions
- TBD
> MLIBZ-2445: Live Service messages not coming with strict permissions

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey.xcodeproj/xcshareddata/xcschemes/Kinvey.xcscheme
- Kinvey/Kinvey/DeviceInfo.swift
- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/KinveyTests/ClientTestCase.swift
- Kinvey/KinveyTests/NetworkStoreTests.swift
`X-Kinvey-Device-Info` header using JSON format
- `X-Kinvey-Device-Info` replaces the old `X-Kinvey-Device-Information`
- Unit test to check if the header is being sent and checking if the properties are present
> MLIBZ-2465: X-Kinvey-Device-Info header

- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/Kinvey/MIC.swift
- Kinvey/Kinvey/RequestFactory.swift
- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/UserTests.swift
OAuth Resource Owner password grant flow
https://devcenter.kinvey.com/rest/guides/mobile-identity-connect#resource-owner-grant
Basically it simplifies the steps to login using MIC using username/password
- `MIC` and `User` classes have new methods. Old methods handling the old headless way of login are now deprecated
- Unit Test added
> MLIBZ-2253: oauth resource owner password grant

- scripts/api-diff/.gitignore
- scripts/api-diff/Package.resolved
- scripts/api-diff/Package.swift
- scripts/api-diff/README.md
- scripts/api-diff/Sources/api-diff/main.swift
Generate API Diffs between releases
- No changes to the SDK code
- No need since no changes were made to the SDK code
> MLIBZ-2539: api diff tool

- Kinvey/KinveyTests/NetworkStoreTests.swift
Additional unit test for auto-pagination
- No changes
- Some additional checks for the unit test
> MLIBZ-2584: additional unit test for auto-pagination

- .travis.yml
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyAppUITests/KinveyAppUITests.swift
- Makefile
Inconsistent cache results bugfix
- Refreshing the cache before use
- Current unit tests actually detected this issue
> MLIBZ-2638: Inconsistent cache results bugfix

- Kinvey/Kinvey/RealmCache.swift
- Kinvey/KinveyTests/Person.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Cascade Delete should not delete references that are being used by other objects
- Cascade Delete method
- A few unit tests added to cover cases where objects are deleted, but their references should not be deleted
> MLIBZ-2655: Cascade Delete References

- Kinvey/Kinvey/Client.swift
- Kinvey/KinveyTests/EncryptedDataStoreTestCase.swift
Adding a overload method for instanceId and encrypted
- New overload constructor for `Client`
- Unit test checking the `instanceId` network calls and the cache encryption
> MLIBZ-2678: adding a overload method for instanceId and encrypted

- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/UserTests.swift
Codable support for Social Identities
- `UserSocialIdentity` now support `Codable`
- Checking if decode and encode are working for social identities
> MLIBZ-2672: Codable support for Social Identities

- Kinvey/Kinvey/Kinvey.xcconfig
Adding support for the new Apple Watch arch
- no changes in the code
- same unit tests
> MLIBZ-2721: Adding support for the new Apple Watch

- Kinvey/Kinvey/Geolocation.swift
- Kinvey/KinveyTests/EntityTestCase.swift
GeoPoint Codable Support
- `GeoPoint` was not doing `encode()` and `decode()` correctly when `Codable` is used
- Testing `encode()` and `decode()` methods for `GeoPoint`
> MLIBZ-2724: GeoPoint Codable Support

- .travis.yml
- Kinvey/Kinvey/RealmCache.swift
Small change but allows cover from an error
- Open Realm does not force `try!`
> MLIBZ-2828: Crashing during open Realm not allowing recovery

- .travis.yml
- Kinvey/Kinvey/Cache.swift
- Kinvey/Kinvey/FindOperation.swift
- Kinvey/Kinvey/Kinvey.swift
- Kinvey/Kinvey/ObjectMapperJSONParser.swift
- Kinvey/Kinvey/Query.swift
- Kinvey/Kinvey/RealmCache.swift
- Kinvey/Kinvey/RealmSync.swift
- Kinvey/Kinvey/RemoveOperation.swift
- Kinvey/KinveyTests/Person.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
Cascade Delete performance improvement
- Improvements made by avoid lookups into the database schema
- Scenario added to existing tests
> MLIBZ-2824: Cascade Delete performance improvement

- .swiftlint.yml
- Kinvey/Kinvey/DataStore.swift
- Kinvey/KinveyTests/MockKinveyBackend.swift
Change the value for Delta Set in the DataStore not working as it should
- We were ignoring the `newValue` and always set `true`
- TBD
> MLIBZ-2883: Delta Set in the DataStore not working

- Kinvey/Kinvey/Client.swift
- Kinvey/Kinvey/CustomEndpoint.swift
- Kinvey/Kinvey/DataStore.swift
- Kinvey/Kinvey/Error.swift
- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/FindOperation.swift
- Kinvey/Kinvey/MIC.swift
- Kinvey/Kinvey/PubNubRealtimeRouter.swift
- Kinvey/Kinvey/PurgeOperation.swift
- Kinvey/Kinvey/Push.swift
- Kinvey/Kinvey/PushOperation.swift
- Kinvey/Kinvey/ReadOperation.swift
- Kinvey/Kinvey/Realtime.swift
- Kinvey/Kinvey/Result.swift
- Kinvey/Kinvey/SyncOperation.swift
- Kinvey/Kinvey/User.swift
- Kinvey/Kinvey/WriteOperation.swift
- Kinvey/KinveyTests/CacheStoreTests.swift
- Kinvey/KinveyTests/KinveyTestCase.swift
- Kinvey/KinveyTests/SyncStoreTests.swift
- Kinvey/KinveyTests/UserTests.swift
Replacing Result enum in favor of the one available in Swift 5
- Core code and adjustments in the unit test
> MLIBZ-3001: Swift 5 Result enum

- Kinvey/Kinvey.xcodeproj/project.pbxproj
- Kinvey/Kinvey/AggregateOperation.swift
- Kinvey/Kinvey/Client.swift
- Kinvey/Kinvey/CountOperation.swift
- Kinvey/Kinvey/CustomEndpoint.swift
- Kinvey/Kinvey/CustomEndpointParams.swift
- Kinvey/Kinvey/DataStore.swift
- Kinvey/Kinvey/Endpoint.swift
- Kinvey/Kinvey/FileStore.swift
- Kinvey/Kinvey/FindOperation.swift
- Kinvey/Kinvey/GetOperation.swift
- Kinvey/Kinvey/HttpRequest.swift
- Kinvey/Kinvey/HttpRequestFactory.swift
- Kinvey/Kinvey/MIC.swift
- Kinvey/Kinvey/PurgeOperation.swift
- Kinvey/Kinvey/Push.swift
- Kinvey/Kinvey/PushOperation.swift
- Kinvey/Kinvey/RemoveByIdOperation.swift
- Kinvey/Kinvey/RemoveByQueryOperation.swift
- Kinvey/Kinvey/RequestFactory.swift
- Kinvey/Kinvey/Result.swift
- Kinvey/Kinvey/SaveOperation.swift
- Kinvey/Kinvey/User.swift
- Kinvey/KinveyTests/AutoDataStoreSpec.swift
- Kinvey/KinveyTests/KinveyTestCase.swift
Codebeat improvements removing the majority of `Critical` issues
- No semantic code changes
> Codebeat improvements

- Kinvey/Kinvey/FileStore.swift
- Kinvey/KinveyTests/AutoDataStoreSpec.swift
- Kinvey/KinveyTests/KinveyTestCase.swift
- Kinvey/KinveyTests/KinveyURLProtocol.swift
Bugfix for Auto File Store Type
- `FileStore` missing some key points for `Auto` Store
- Adding a file store test to the Auto Test Suite
> MLIBZ-3079: Auto File Store Type

- LICENSE
> Updating LICENSE file

- Kinvey/Kinvey/SaveMultiOperation.swift
- Kinvey/KinveyTests/MultiInsertSpec.swift
Fixing Index for Errors when multiple requests are necessary
- Errors now need to be mapped to change the indexes
- Adding a test to check if the index errors are correct
> MLIBZ-3119: Fixing Index for Errors when multiple requests are necessary

- Kinvey/Kinvey/SaveMultiOperation.swift
- Kinvey/KinveyTests/MultiInsertSpec.swift
Steps to reproduce:
1. Create a list with more that 200 items
2. Set the _geoloc params to be invalid for all items between index 99 and 199
3. Save it using multi-insert
Expected result: 3 POST requests for multi-insert are used - the second returns one error for the whole request. The response of the save operation should be an array of entities where items 99 to 199 are null and an array of errors for items 99 to 199 and the reason of their failure.
Actual result: The first POST and third POST requests succeed and its items are created, the second one returns an error. The overall response is the error for invalid params and the user never understands that the first 100 items and the last have been saved
- A `recover()` statement is need to be able to recover when one of the batches …
> MLIBZ-3146, fixing return when an entire batch fails
